### PR TITLE
Test on Django 4.2

### PR DESCRIPTION
**Pull request by adamchainz**
Update tests to run with Python 3.11 and Django 4.2. Checked for warnings by adding `-W all` to the test run, one appeared:

```
/.../site-packages/django/conf/__init__.py:241: RemovedInDjango50Warning: The default value of USE_TZ will change from False to True in Django 5.0. Set USE_TZ to False in your project settings if you want to keep the current default behavior.
  warnings.warn(
```

...which I fixed.

I also upgraded the GitHub Actions actions.

### CODE REVIEW

**Comment by pablop94** [comment]
Hey! thanks for the update and sorry for the delay, could you please remove 3.6 and 3.7 from github actions?

**Comment by adamchainz** [comment]
Done. (Did you know you maintainers push changes to PR branches?)

**Comment by pablop94** [comment]
No, I didn't know, I'll do it next time. Thanks for all!

**Comment by pablop94** [comment]
You'll need a new release, right? If so, I'll be releasing it later today

**Comment by adamchainz** [comment]
I don't *need* it, since the code was compatible without changes. But to show your project is active and definitely works on the latest version, you can release.

**Pull request merged**
